#!/usr/bin/env sh

docker run \
	--rm \
	--tty \
	--interactive \
	--init \
	--workdir /root \
	--mount type=bind,src=/etc/localtime,target=/etc/localtime,readonly \
	--mount type=bind,src=$PWD,dst=/root \
	--mount type=bind,src=/tmp/$USER/tmux.socket,dst=/tmp/tmux.socket \
	--mount type=bind,src=$TMUX_SESSIONS_DIR,dst=/root/.tmuxp \
	tmuxp 
	load -S $TMUX_SOCKET "$@"
