#!/usr/bin/env sh

docker run \
	--rm \
	--tty \
	--interactive \
	--init \
	--name graphviz \
	--mount type=bind,src=/etc/localtime,target=/etc/localtime,readonly \
	--mount type=bind,src=$PWD,target=/root \
	--workdir /root \
	graphviz "$@"
